import React from "react";
import GameCard from "./gameCard";
import { Container, Row, Col } from "react-bootstrap";
import "./gamesPanel.css";
import ronaldinho from "../../assets/ronaldinho.jpg";

const games = [
  {
    league: "League A: Eagles Cup",
    teams: "Bill FC vs Memo FC",
    date: "Nov 18th, 2024",
    time: "7:00 PM - 7:50 PM (50min)",
    location: "Soccer Park",
    address: "123 Soccer Ave, Houston, TX",
    mapLink: "https://maps.google.com/?q=Soccer Park Houston TX",
    type: "Indoor",
    cost: "8.99",
    age: "17+",
    leagueDates: "May 8 - Jun 25, 2022",
    leagueFormat: "8-Week Single Season",
    specs: "5 vs 5\n5 of 16 players\nCoEd",
    contactName: "John Doe",
    contactPhone: "832.395.7130",
    contactEmail: "john.doe@example.com",
    image: ronaldinho,
  },
  {
    league: "League B: Champions Cup",
    teams: "Alpha FC vs Omega FC",
    date: "Nov 20th, 2024",
    time: "6:00 PM - 6:50 PM (50min)",
    location: "Football Arena",
    address: "456 Football St, Houston, TX",
    mapLink: "https://maps.google.com/?q=Football Arena Houston TX",
    type: "Outdoor",
    cost: "10.99",
    age: "18+",
    leagueDates: "May 8 - Jun 25, 2022",
    leagueFormat: "8-Week Single Season",
    specs: "7 vs 7\n7 of 20 players\nCoEd",
    contactName: "Jane Smith",
    contactPhone: "832.395.7131",
    contactEmail: "jane.smith@example.com",
    image: ronaldinho,
  },
  {
    league: "League C: Warriors Cup",
    teams: "Lions FC vs Tigers FC",
    date: "Nov 25th, 2024",
    time: "8:00 PM - 8:50 PM (50min)",
    location: "Stadium Central",
    address: "789 Stadium Blvd, Houston, TX",
    mapLink: "https://maps.google.com/?q=Stadium Central Houston TX",
    type: "Indoor",
    cost: "9.99",
    age: "16+",
    leagueDates: "May 8 - Jun 25, 2022",
    leagueFormat: "8-Week Single Season",
    specs: "6 vs 6\n6 of 18 players\nCoEd",
    contactName: "Bill Johnson",
    contactPhone: "832.395.7132",
    contactEmail: "bill.johnson@example.com",
    image: ronaldinho,
  },
  {
    league: "League D: Legends Cup",
    teams: "Heroes FC vs Villains FC",
    date: "Dec 1st, 2024",
    time: "5:00 PM - 5:50 PM (50min)",
    location: "Heroes Park",
    address: "101 Heroes Rd, Houston, TX",
    mapLink: "https://maps.google.com/?q=Heroes Park Houston TX",
    type: "Outdoor",
    cost: "11.99",
    age: "15+",
    leagueDates: "May 8 - Jun 25, 2022",
    leagueFormat: "8-Week Single Season",
    specs: "5 vs 5\n5 of 16 players\nCoEd",
    contactName: "Alice Brown",
    contactPhone: "832.395.7133",
    contactEmail: "alice.brown@example.com",
    image: ronaldinho,
  },
  {
    league: "League E: Battle Cup",
    teams: "Knights FC vs Dragons FC",
    date: "Dec 5th, 2024",
    time: "4:00 PM - 4:50 PM (50min)",
    location: "Dragon Arena",
    address: "202 Dragon Ln, Houston, TX",
    mapLink: "https://maps.google.com/?q=Dragon Arena Houston TX",
    type: "Indoor",
    cost: "8.99",
    age: "17+",
    leagueDates: "May 8 - Jun 25, 2022",
    leagueFormat: "8-Week Single Season",
    specs: "5 vs 5\n5 of 16 players\nCoEd",
    contactName: "Chris Evans",
    contactPhone: "832.395.7134",
    contactEmail: "chris.evans@example.com",
    image: ronaldinho,
  },
  {
    league: "League F: Ultimate Cup",
    teams: "Eagles FC vs Hawks FC",
    date: "Dec 10th, 2024",
    time: "3:00 PM - 3:50 PM (50min)",
    location: "Eagle Stadium",
    address: "303 Eagle Dr, Houston, TX",
    mapLink: "https://maps.google.com/?q=Eagle Stadium Houston TX",
    type: "Outdoor",
    cost: "9.99",
    age: "16+",
    leagueDates: "May 8 - Jun 25, 2022",
    leagueFormat: "8-Week Single Season",
    specs: "7 vs 7\n7 of 20 players\nCoEd",
    contactName: "David White",
    contactPhone: "832.395.7135",
    contactEmail: "david.white@example.com",
    image: ronaldinho,
  },
  {
    league: "League G: Victory Cup",
    teams: "Sharks FC vs Dolphins FC",
    date: "Dec 15th, 2024",
    time: "2:00 PM - 2:50 PM (50min)",
    location: "Ocean Park",
    address: "404 Ocean Rd, Houston, TX",
    mapLink: "https://maps.google.com/?q=Ocean Park Houston TX",
    type: "Indoor",
    cost: "10.99",
    age: "18+",
    leagueDates: "May 8 - Jun 25, 2022",
    leagueFormat: "8-Week Single Season",
    specs: "6 vs 6\n6 of 18 players\nCoEd",
    contactName: "Emily Davis",
    contactPhone: "832.395.7136",
    contactEmail: "emily.davis@example.com",
    image: ronaldinho,
  },
  {
    league: "League H: Champions League",
    teams: "Warriors FC vs Guardians FC",
    date: "Dec 20th, 2024",
    time: "1:00 PM - 1:50 PM (50min)",
    location: "Guardians Arena",
    address: "505 Guardians St, Houston, TX",
    mapLink: "https://maps.google.com/?q=Guardians Arena Houston TX",
    type: "Outdoor",
    cost: "8.99",
    age: "17+",
    leagueDates: "May 8 - Jun 25, 2022",
    leagueFormat: "8-Week Single Season",
    specs: "5 vs 5\n5 of 16 players\nCoEd",
    contactName: "Frank Miller",
    contactPhone: "832.395.7137",
    contactEmail: "frank.miller@example.com",
    image: ronaldinho,
  },
  {
    league: "League I: Elite Cup",
    teams: "Panthers FC vs Cougars FC",
    date: "Dec 25th, 2024",
    time: "12:00 PM - 12:50 PM (50min)",
    location: "Elite Stadium",
    address: "606 Elite Blvd, Houston, TX",
    mapLink: "https://maps.google.com/?q=Elite Stadium Houston TX",
    type: "Indoor",
    cost: "11.99",
    age: "16+",
    leagueDates: "May 8 - Jun 25, 2022",
    leagueFormat: "8-Week Single Season",
    specs: "6 vs 6\n6 of 18 players\nCoEd",
    contactName: "Grace Lee",
    contactPhone: "832.395.7138",
    contactEmail: "grace.lee@example.com",
    image: ronaldinho,
  },
  {
    league: "League J: Pro Cup",
    teams: "Giants FC vs Titans FC",
    date: "Dec 30th, 2024",
    time: "11:00 AM - 11:50 AM (50min)",
    location: "Titan Park",
    address: "707 Titan Rd, Houston, TX",
    mapLink: "https://maps.google.com/?q=Titan Park Houston TX",
    type: "Outdoor",
    cost: "9.99",
    age: "15+",
    leagueDates: "May 8 - Jun 25, 2022",
    leagueFormat: "8-Week Single Season",
    specs: "5 vs 5\n5 of 16 players\nCoEd",
    contactName: "Henry Wilson",
    contactPhone: "832.395.7139",
    contactEmail: "henry.wilson@example.com",
    image: ronaldinho,
  },
];

const GamesPanel = () => {
  return (
    <Container>
      <h1 className="games-header">Games Schedule</h1>
      <Row>
        {games.map((game, index) => (
          <Col md={12} key={index}>
            <GameCard game={game} />
          </Col>
        ))}
      </Row>
    </Container>
  );
};

export default GamesPanel;
